appName: goalkeeper

postgres:
  enabled: true
  image: postgres:9.6-alpine
  dbName: goalkeeper
  storage:
    size:
      limited: true
      value: 4Gi
  secrets:
    user:
      name: db-user
      key: username
    password:
      name: db-user-pass
      key: password

redis: 
  enabled: false
  image: redis:3.2-alpine

migration:
  enabled: true
  args: ['rails db:migrate']
  createDb:
    args: ['rails db:create || true']
ingress:
  hostname: goalkeeper-search.ru

app:
  image: ghcr.io/musicguns/goalkeepers_search:latest
  args: ['rails s -p 3000 -b 0.0.0.0']
  activeStorage:
    enabled: true
    size: 2Gi
  secrets:
    secretKeyBase:
      name: secret-key-base
      key: secret-key-base
  nginx:
    image: ghcr.io/musicguns/goalkeepers_search_nginx:latest
